### ISSUE TITLE
Add container WOD page to sort by Benchmark, Hero, Camille, and Wodstar

### ISSUE THREAD

**Issue by lauragagliano** [asu-cis-capstone/crossfit#80]

**Comment by krisser** [comment]
So we would need to make a general WOD page that had buttons for Benchmark, Hero, Camille, and Wostar? And then 4 layouts for each of those categories with images populated?

**Comment by lauragagliano** [comment]
Yes, image buttons. Otherwise the WOD page will be absolutely unmanageable, like the one on their site already is. The Camille one will need to re-direct to the website for them to pay for. The Wodstar one will need to dynamically load from Azure, but the Hero and Benchmark ones should be fine hardcoded in.

**Comment by krisser** [comment]
Ok sounds good.

**Comment by lauragagliano** [comment]
I also changed the WOD layout, let me send you a picture.

**Comment by krisser** [comment]
Ok. You may send me a picture.

**Comment by lauragagliano** [comment]
Check your phone
