### ISSUE TITLE
User profile picture needs to be pulled from Facebook and stored

### ISSUE THREAD

**Issue by lauragagliano** [asu-cis-capstone/crossfit#85]

**Comment by stevbev** [comment]
Would it be more prudent to just show the profile picture from the social media session, instead of building a new mechanism to retrieve, store, and maintain the image in our database?

**Comment by lauragagliano** [comment]
It's basically the same thing - my thought on storing it would be to avoid
having to make the call every time, but if we're just showing it on the
user journal than I guess it's the same thing. Looks like you just
implement a ProfilePictureView and the FB API encapsulates the process so
that you CAN'T store the image.
